version: "3.9"
services:
  jobrunner:
    image: zaptross/zapcode-jobrunner:latest
    restart: unless-stopped
    build:
      context: ./jobrunner
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: "mongo"
    env_file:
      - .env

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@mongo:${DATABASE_PORT}/
